export interface MenuItem {
  name: string;
  price: number;
  isStudentChoice?: boolean;
}

export interface MenuCategory {
  category: string;
  items: MenuItem[];
}

export interface Restaurant {
  id: string;
  name: string;
  image: string;
  rating: number;
  description: string;
  categories: string[];
  bestItem: string;
  menu: MenuCategory[];
}

export const restaurants: Restaurant[] = [
  {
    id: 'haleem',
    name: 'Haleem',
    image: 'assets/images/haleem.jpg',
    rating: 5,
    description: 'Slow-cooked by tradition, seasoned with love, and perfected by time.',
    categories: ['Haleem'],
    bestItem: 'Mutton Haleem',
    menu: [
      {
        category: "Student's Choice",
        items: [
          { name: 'Mutton Haleem (1/4 kg)', price: 210, isStudentChoice: true },
        ],
      },
      {
        category: "Haleem",
        items: [
          { name: 'Mutton Haleem(1/4 kg)', price: 210},
          { name: 'Mutton Haleem(1/2 kg)', price: 360},
          { name: 'Mutton Haleem(1 kg)', price: 710},
          // { name: 'Chicken Haleem (1/4 kg)', price: 200},
          // { name: 'Chicken Haleem (1/2 kg)', price: 200},
          // { name: 'Chicken Haleem (1 kg)', price: 200},
        ],
      },
    ]
  },
  {
    id: 'Amrutha',
    name: 'Amrutha (Earlier Nellore Ruchulu)',
    image: 'assets/images/amrutha.jpeg',
    rating: 5,
    
    description: 'Mughalai Birynai is Famous Here',
    categories: ['Biryani'],
    bestItem: 'Mughalai Biryani',
    menu: [
      {
        category: "Student's Choice",
        items: [
          { name: 'Dum Biryani', price: 199, isStudentChoice: true },
        ],
      },
      {
        category: "Biryani",
        items: [
          { name: 'Dum Biryani', price: 199},
          { name: 'Fry Piece Biryani', price: 219},
          { name: 'Mixed Biryani', price: 219},
          { name: 'Mughalai Biryani', price: 239},
          { name: 'Sp Mixed Biryani', price: 279},
        
          // { name: 'Chicken Haleem (1/2 kg)', price: 200},
          // { name: 'Chicken Haleem (1 kg)', price: 200},
        ],
      },
    ]
  },
  {
    id: 'RoyalGrand',
    name: 'Hotel Royal Grand',
    image: 'assets/images/royalgrand.png',
    rating: 5,
    description: 'Lollipop Biryani is famous here',
    categories: ['Biryani'],
    bestItem: 'Lollipop Biryani',
    menu: [
      {
        category: "Student's Choice",
        items: [
          { name: 'Lollipop Biryani', price: 269, isStudentChoice: true },
        ],
      },
      {
        category: "Biryani",
        items: [
          { name: 'Dum Biryani', price: 199},
          { name: 'Fry Piece Biryani', price: 219},
          { name: 'Lollipop Biryani', price: 269},
          { name: 'Wing Biryani', price: 269},
          { name: 'Mughalai Biryani', price: 269},
          { name: 'Tikka Biryani', price: 269},
          { name: 'Sp Biryani', price: 269},
          
        
          // { name: 'Chicken Haleem (1/2 kg)', price: 200},
          // { name: 'Chicken Haleem (1 kg)', price: 200},
        ],
      },
    ]
  },

  {
    id: 'spice-magic',
    name: 'Spice Magic',
    image: 'assets/images/spice-magic.jpg',
    rating: 4,
    description: 'Famous for their aromatic Mixed Biryani',
    categories: ['Biryani', 'Fast Food'],
    bestItem: 'Mixed Biryani',
    menu: [
      {
        category: "Student's Choice",
        items: [{ name: 'Mixed Biryani', price: 190, isStudentChoice: true },
                { name: 'chicken 65 Biryani', price: 240, isStudentChoice: true  },
                { name: 'Boxer Fried Rice', price: 260, isStudentChoice: true  },
                //{ name: 'SP Fried Rice', price: 250, isStudentChoice: true  },
        ],

      },
      {
        category: "Newly Added",
        items: [{ name: 'Chicken 65 Biryani', price: 240},
                { name: 'Mughalai Biryani', price: 250},
                { name: 'Chicken Special biryani', price: 240},
               // { name: 'Boxer Fried Rice', price: 260},
                //{ name: 'SP Fried Rice', price: 250},
        ],

      },

      
      {
        category: 'Bucket Biryanis',
        items: [
          { name: 'Bucket Dum Biryani (For 4)', price: 640 },
          { name: 'Bucket Fry Piece Biryani (For 4)', price: 670 },
          { name: 'Bucket Mixed Biryani (For 4)', price: 730 },
        ],
      },
      {
        category: 'Biryanis',
        items: [
          { name: 'Dum Biryani', price: 160 },
          { name: 'Fry Biryani', price: 180 },
          {name: 'Mixed Biryani', price: 190},
          { name: 'Chicken 65 biryani', price: 240 },
          { name: 'Chicken Special biryani', price: 240 },
          { name: 'Mughalai Biryani', price: 250 },
        ],
      },
      
      {
        category: 'Chinese/Fast Food',
        items: [
          { name: 'Veg Noodles', price: 90 },
          { name: 'Veg Fried Rice', price: 90 },
          { name: 'Egg Noodles', price: 110 },
          { name: 'Egg Fried Rice', price: 110 },
          { name: 'Chicken Noodles', price: 130 },
          { name: 'Chicken Fried Rice', price: 130 },
         // { name: 'SP Fried Rice', price: 20 },
         // { name: 'Boxer Fried Rice', price: 250 },
          { name: 'Chicken Manchurian', price: 160 },
          { name: 'Chilli Chicken', price: 160 },
          { name: 'Chicken Lollipop (4 pcs)', price: 160 },
        ],
      },
    ],
  },
  {
    id: 'food-corner',
    name: 'Food Corner',
    image: 'assets/images/food-corner.jpg',
    rating: 4,
    description: 'Your go-to spot for quick Chinese & Fast Foods',
    categories: ['Fast Food'],
    bestItem: 'Chicken Noodles',
    menu: [
      {
        category: "Student's Choice",
        items: [
          { name: 'Veg Noodles', price: 80, isStudentChoice: true },
          { name: 'Egg Noodles', price: 90, isStudentChoice: true },
          { name: 'Chicken Noodles', price: 100, isStudentChoice: true },
        ],
      },
      {
        category: 'Noodles',
        items: [
          { name: 'Veg Noodles', price: 80 },
          { name: 'Egg Noodles', price: 90 },
          { name: 'Chicken Noodles', price: 100 },
          { name: 'Veg Manchurian Noodles', price: 90 },
          { name: 'Egg Manchurian Noodles', price: 100 },
        ],
      },
      {
        category: 'Fried Rice',
        items: [
          { name: 'Veg Fried Rice', price: 80 },
          { name: 'Egg Fried Rice', price: 90 },
          { name: 'Chicken Fried Rice', price: 100 },
          { name: 'Veg Manchurian Fried Rice', price: 90 },
          { name: 'Egg Manchurian Fried Rice', price: 100 },
        ],
      },
      {
        category: 'Starters',
        items: [
          { name: 'Veg Manchurian', price: 80 },
          { name: 'Egg Manchurian', price: 90 },
          { name: 'Chicken Manchurian', price: 170 },
          { name: 'Chilli Chicken', price: 170 },
          { name: '4P Chicken Lollipop', price: 150 },
        ],
      },
    ],
  },
  {
    id: 'hotel-bheemasena',
    name: 'Hotel Bheemasena',
    image: 'assets/images/hotel-bheemasena.jpg',
    rating: 5,
    description: 'Authentic restaurant-style veg and non-veg dishes',
    categories: ['Biryani', 'Veg Meals'],
    bestItem: 'Biryanis, Starters, Soups & Curries',
    menu: [
      {
        category: 'Veg Biryanis',
        items: [
          { name: 'Biryani Rice', price: 180 },
          { name: 'Veg Biryani', price: 260 },
          { name: 'Spl Veg Biryani', price: 280 },
          { name: 'Ulavacharu Biryani', price: 290 },
          { name: 'Kaju Biryani', price: 310 },
          { name: 'Spl Kaju Biryani', price: 330 },
          { name: 'Mushroom Biryani', price: 290 },
          { name: 'Spl Mushroom Biryani', price: 310 },
          { name: 'Paneer Biryani', price: 290 },
          { name: 'Spl Paneer Biryani', price: 310 },
          { name: 'Paneer Tikka Biryani', price: 330 },
          { name: 'Bheemasena Spl Biryani', price: 340 },
        ],
      },
      {
        category: 'Non-Veg Biryanis',
        items: [
          { name: 'Spl Egg Biryani', price: 280 },
          { name: 'Chicken Dum Biryani', price: 300 },
          { name: 'Chicken Fry Biryani', price: 300 },
          { name: 'Chicken Fry Roasted Biryani', price: 310 },
          { name: 'Spl Chicken Biryani', price: 320 },
          { name: 'Joint Biryani', price: 330 },
          { name: 'Kalmi Biryani', price: 340 },
          { name: 'Chicken Tikka Biryani', price: 340 },
          { name: 'Chicken Mughlai Biryani', price: 330 },
          { name: 'Ulavacharu Chicken Biryani', price: 340 },
          { name: 'Wings Biryani', price: 330 },
          { name: 'Chicken Lollipop Biryani', price: 350 },
          { name: 'Kundan Biryani', price: 380 },
          { name: 'Nawab Biryani', price: 390 },
          { name: 'Tandoori Chicken Biryani', price: 390 },
          { name: 'Oanpur Biryani', price: 420 },
          { name: 'Nalli Gosht', price: 520 },
          { name: 'Mutton Fry Biryani', price: 420 },
          { name: 'Mutton Afgani Biryani', price: 420 },
          { name: 'Mutton Dum Biryani', price: 430 },
          { name: 'Mutton Keema Biryani', price: 500 },
          { name: 'Mutton Mughlai Biryani', price: 450 },
          { name: 'Prawns Biryani', price: 410 },
          { name: 'Spl Prawns Biryani', price: 430 },
          { name: 'Fish Biryani', price: 410 },
          { name: 'Bheemasena Spl Non Veg Biryani', price: 480 },
        ],
      },
      {
        category: 'Bucket Biryanis',
        items: [
          { name: 'Chicken Dum Bucket Biryani', price: 850 },
          { name: 'Fry Chicken Bucket Biryani', price: 870 },
          { name: 'Spl Chicken Bucket Biryani', price: 900 },
          { name: 'Wings Bucket Biryani', price: 910 },
          { name: 'Lollipop Bucket Biryani', price: 970 },
          { name: 'Kundan Bucket Biryani', price: 1170 },
          { name: 'Prawns Bucket Biryani', price: 1120 },
          { name: 'Fish Bucket Biryani', price: 1100 },
          { name: 'Mutton Bucket Biryani', price: 1250 },
        ],
      },
      {
        category: 'Mini Biryanis',
        items: [
          { name: 'Mini Dum Biryani', price: 190 },
          { name: 'Mini Fry Biryani', price: 190 },
          { name: 'Mini Boneless Biryani', price: 200 },
          { name: 'Mini Paneer Biryani', price: 200 },
          { name: 'Mini Mushroom Biryani', price: 190 },
        ],
      },
      {
        category: 'Fried Rice',
        items: [
          { name: 'Zeera Rice', price: 230 },
          { name: 'Veg Fried Rice', price: 250 },
          { name: 'Paneer Fried Rice', price: 280 },
          { name: 'Kaju Fried Rice', price: 290 },
          { name: 'Mushroom Fried Rice', price: 270 },
          { name: 'Bheemasena Spl Fried Rice', price: 330 },
          { name: 'Egg Fried Rice', price: 280 },
          { name: 'Chicken Fried Rice', price: 300 },
          { name: 'Spl Chicken Fried Rice', price: 320 },
          { name: "Prawn's Fried Rice", price: 350 },
          { name: 'Mutton Fried Rice', price: 380 },
          { name: 'Bheemasena Spl Non Veg Fried Rice', price: 410 },
        ],
      },
      // {
      //   category: 'Soups',
      //   items: [
      //     { name: 'Veg Corn Soup', price: 130 },
      //     { name: 'Veg Manchow Soup', price: 130 },
      //     { name: 'Veg H/S Soup', price: 130 },
      //     { name: 'Bheemasena Spl Soup (Veg)', price: 140 },
      //     { name: 'Chicken Corn Soup', price: 140 },
      //     { name: 'Chicken Manchow Soup', price: 140 },
      //     { name: 'Chicken H/S Soup', price: 140 },
      //     { name: 'Chicken Coriander Soup', price: 140 },
      //     { name: 'Mutton Bone Soup', price: 170 },
      //     { name: 'Mutton Sharbh Soup', price: 170 },
      //     { name: 'Bheemasena Spl Soup (Non-Veg)', price: 160 },
      //   ],
      // },
      {
        category: 'Starters',
        items: [
          { name: 'Veg Manchuria', price: 210 },
          { name: 'Gobi Manchuria', price: 210 },
          { name: 'Chilli Mushroom', price: 230 },
          { name: 'Crispy Baby Corn', price: 250 },
          { name: 'Paneer-65', price: 280 },
          { name: 'Paneer Majestic', price: 290 },
          { name: 'Golden Fried Paneer', price: 290 },
          { name: 'Paneer Tikka', price: 330 },
          { name: 'Bheemasena Spl Veg', price: 330 },
          { name: 'Chilli Chicken', price: 290 },
          { name: 'Chicken Manchuria', price: 290 },
          { name: 'Chicken 65', price: 290 },
          { name: 'Chicken Majestic', price: 290 },
          { name: 'Dragon Chicken', price: 300 },
          { name: 'Chicken 555', price: 290 },
          { name: 'Royal Chicken', price: 300 },
          { name: 'Chicken Lollipop', price: 310 },
          { name: 'Apollo Fish', price: 330 },
          { name: 'Chilli Fish', price: 340 },
          { name: 'Bheemasena Spl Non Veg', price: 360 },
          { name: 'Chicken Wings', price: 310 },
          { name: 'Basket Chicken', price: 320 },
          { name: 'Chicken Fry Bone', price: 270 },
          { name: 'Chicken Popcorn', price: 290 },
          { name: 'Chilli Egg', price: 250 },
          { name: 'Crispy Chicken', price: 310 },
          { name: 'Hong Kong Chicken', price: 300 },
          { name: 'Pepper Chicken', price: 320 },
          { name: 'Loose Prawns', price: 360 },
          { name: 'Chilli Prawn', price: 370 },
        ],
      },
      {
        category: 'Curries',
        items: [
          { name: 'Plain Palak/Paneer', price: 190 },
          { name: 'Mix Veg Curry', price: 270 },
          { name: 'Paneer Butter M/S', price: 280 },
          { name: 'Kaju Masala', price: 300 },
          { name: 'Mushroom Masala', price: 280 },
          { name: 'Kaju Paneer Curry', price: 300 },
          { name: 'Veg Jaipuri', price: 280 },
          { name: 'Veg Chat Pat', price: 290 },
          { name: 'Tomato Kaju Curry', price: 300 },
          { name: 'Methi Chaman', price: 300 },
          { name: 'Bheemasena Spl Veg Curry', price: 330 },
          { name: 'Chicken Curry', price: 270 },
          { name: 'Chicken Fry Bone Curry', price: 260 },
          { name: 'Egg Burji', price: 190 },
          { name: 'Egg Curry', price: 230 },
          { name: 'Methi Chicken Curry', price: 290 },
          { name: 'Mughlai Chicken Curry', price: 290 },
          { name: 'Mutton Boneless Curry', price: 410 },
          { name: 'Prawns Fry', price: 350 },
          { name: 'Andhra Chicken Curry', price: 290 },
          { name: 'Kadai Chicken', price: 290 },
          { name: 'Butter Chicken', price: 290 },
          { name: 'Hyderabad Chicken', price: 290 },
          { name: 'Chicken Tikka Masala', price: 290 },
          { name: 'Punjabi Chicken Masala', price: 310 },
          { name: 'Prawns Curry', price: 350 },
          { name: 'Mutton Curry', price: 380 },
          { name: 'Fish Curry BL', price: 330 },
          { name: 'Mutton Rogan Josh', price: 410 },
          { name: 'Bheemasena Spl N.V. Curry', price: 400 },
        ],
      },
      {
        category: 'Breads',
        items: [
          { name: 'Pulka', price: 15 },
          { name: 'Butter Pulka', price: 20 },
          { name: 'Roti', price: 25 },
          { name: 'Butter Roti', price: 30 },
          { name: 'Butter Naan', price: 45 },
          { name: 'Plain Naan', price: 35 },
          { name: 'Kulcha', price: 50 },
          { name: 'M/S Kulcha', price: 60 },
          { name: 'Methi Parota', price: 60 },
          { name: 'Garlic Naan', price: 70 },
        ],
      },
      {
        category: 'Tandoori Starters',
        items: [
          { name: 'Tandoori Chicken 1/2', price: 300 },
          { name: 'Tandoori Chicken Full', price: 580 },
          { name: 'Tangdi Kebab', price: 330 },
          { name: 'Chicken Tikka', price: 310 },
          { name: 'Malai Tikka', price: 340 },
          { name: 'Fish Tikka', price: 330 },
        ],
      },
      {
        category: 'Thali/Beverages',
        items: [
          { name: 'Thali', price: 140 },
          { name: 'Thali Parcel', price: 160 },
          { name: 'Thali Parcel Single', price: 130 },
          { name: 'Ragi Sangati', price: 110 },
          { name: 'Natukodi Curry', price: 350 },
          { name: 'White Rice', price: 80 },
          { name: 'Curd Rice', price: 90 },
          { name: 'Spl Curd Rice', price: 150 },
          { name: 'Water Bottle', price: 20 },
          { name: 'Soft Drink', price: 25 },
          { name: 'Butter Milk', price: 50 },
          { name: 'Lassi', price: 70 },
        ],
      },
    ],
  },
  {
    id: 'palleturu-palahaaram',
    name: 'Palleturu Palaharam',
    image: 'assets/images/palleturu-palahaaram.jpg',
    rating: 4,
    description: 'Authentic village-style non-veg biryani delicacies',
    categories: ['Biryani'],
    bestItem: 'Mutton Biryani & Prawns Biryani',
    menu: [
      {
        category: "Student's Choice(Revised Prices By Restaurent)",
        items: [
          { name: 'Mutton Biryani', price: 320, isStudentChoice: true },
          { name: 'Prawns Biryani', price: 300, isStudentChoice: true },
        ],
      },
      {
        category: 'Full Biryani Menu(Revised Prices By Restaurent)',
        items: [
          { name: 'Mutton Fry Biryani', price: 320 },
          { name: 'Prawns Fry Biryani', price: 300 },
          { name: 'Chicken Dhum Biryani', price: 220 },
          { name: 'Chicken Fry Biryani', price: 250 },
        ],
      },
    ],
  },
  {
    id: 'hotel-mourya',
    name: 'Hotel Mourya',
    image: 'assets/images/hotel-mourya.jpg',
    rating: 4,
    description: 'Home of the legendary Chicken Mughalai Biryani',
    categories: ['Biryani'],
    bestItem: 'Chicken Mughalai Biryani',
    menu: [
      {
        category: "Student's Choice",
        items: [
          { name: 'Chicken Mughalai Biryani', price: 400, isStudentChoice: true },
        ],
      },
      {
        category: 'Non-Veg Biryani',
        items: [
          { name: 'Chicken Dum Biryani', price: 290 },
          { name: 'SP Chicken Biryani', price: 350 },
          { name: 'Chicken Fry Piece Biryani', price: 330 },
          { name: 'Chicken Tikka Biryani', price: 400 },
          { name: 'Chicken Wings Biryani', price: 430 },
          { name: 'Chicken Mughalai Biryani', price: 400 },
          { name: 'Mutton Biryani', price: 530 },
          { name: 'SP Mutton Biryani', price: 620 },
          { name: 'Mutton Mughalai Biryani', price: 580 },
          { name: 'Fish Biryani', price: 490 },
          { name: 'Prawns Biryani', price: 490 },
          { name: 'SP Prawns Biryani', price: 590 },
        ],
      },
      {
        category: 'Mourya Specials',
        items: [
          { name: 'Mourya SP Chicken Biryani', price: 430 },
          { name: 'Mourya SP Mutton Biryani', price: 710 },
          { name: 'Mourya SP Veg Biryani', price: 360 },
          { name: 'Mourya SP Chicken Family Pack', price: 1500 },
          { name: 'Mourya SP Chicken Curry', price: 330 },
        ],
      },
      {
        category: 'Veg Biryani',
        items: [
          { name: 'Biryani Rice', price: 190 },
          { name: 'Biryani Rice Half', price: 140 },
          { name: 'Baby Corn Biryani', price: 240 },
          { name: 'Egg Biryani', price: 280 },
          { name: 'Kaju Biryani', price: 300 },
          { name: 'Mushroom Biryani', price: 270 },
          { name: 'Veg Biryani', price: 260 },
          { name: 'Paneer Biryani', price: 280 },
          { name: 'Veg Palav', price: 240 },
        ],
      },
      {
        category: 'Family Packs',
        items: [
          { name: 'Chicken Dum Family Pack', price: 860 },
          { name: 'Chicken Fry Piece Family Pack', price: 910 },
          { name: 'Chicken SP Family Pack', price: 960 },
          { name: 'Mutton Family Pack', price: 1410 },
          { name: 'Fish Family Pack', price: 1310 },
          { name: 'Prawns Family Pack', price: 1410 },
          { name: 'Veg Family Pack', price: 760 },
        ],
      },
      {
        category: 'Fried Rice',
        items: [
          { name: 'Egg Fried Rice', price: 250 },
          { name: 'SP Egg Fried Rice', price: 300 },
          { name: 'Egg Schezwan Fried Rice', price: 270 },
          { name: 'Ghee Fried Rice', price: 240 },
          { name: 'Kaju Fried Rice', price: 280 },
          { name: 'Mixed Veg Fried Rice', price: 290 },
          { name: 'Mushroom Fried Rice', price: 260 },
          { name: 'Paneer Fried Rice', price: 280 },
          { name: 'Veg Fried Rice', price: 240 },
          { name: 'SP Veg Fried Rice', price: 290 },
          { name: 'Tomato Rice', price: 230 },
          { name: 'Veg Schezwan Fried Rice', price: 240 },
          { name: 'Zeera Rice', price: 220 },
          { name: 'Curd Rice', price: 120 },
          { name: 'SP Curd Rice', price: 170 },
          { name: 'Chicken Fried Rice', price: 280 },
          { name: 'Mixed Non-Veg Fried Rice', price: 330 },
          { name: 'Non-Veg Schezwan Fried Rice', price: 330 },
          { name: 'Mutton Fried Rice', price: 440 },
        ],
      },
      {
        category: 'Snacks',
        items: [
          { name: 'Loose Prawns', price: 360 },
          { name: 'Prawns Fry', price: 360 },
          { name: 'Chilli Fish', price: 360 },
          { name: 'Chilli Prawns', price: 360 },
          { name: 'Apollo Fish', price: 360 },
          { name: 'Baby Corn Manchurian', price: 270 },
          { name: 'Chilli Baby Corn', price: 260 },
          { name: 'Chilli Mushroom', price: 260 },
          { name: 'Chilli Paneer', price: 280 },
          { name: 'Crispy Baby Corn', price: 260 },
          { name: 'Kaju Fry', price: 320 },
          { name: 'Mushroom 65', price: 270 },
          { name: 'Gobi Manchurian', price: 260 },
          { name: 'Paneer 65', price: 280 },
          { name: 'Paneer 555', price: 280 },
          { name: 'Paneer Manchurian', price: 280 },
          { name: 'Paneer Majestic', price: 280 },
          { name: 'Veg Manchurian', price: 260 },
          { name: 'Chicken 555', price: 330 },
          { name: 'Chicken 65', price: 320 },
          { name: 'Chilly Chicken', price: 310 },
          { name: 'Chicken Lollipop', price: 350 },
          { name: 'Chicken Wings Full', price: 340 },
          { name: 'Mutton Fry', price: 470 },
        ],
      },
      {
        category: 'Curries',
        items: [
          { name: 'Andhra Chicken Curry BL', price: 310 },
          { name: 'Butter Chicken', price: 330 },
          { name: 'Chicken Tikka Masala Curry', price: 330 },
          { name: 'Mutton Curry', price: 460 },
          { name: 'Prawns Curry', price: 360 },
          { name: 'Kadai Paneer', price: 280 },
          { name: 'Paneer Butter Masala', price: 270 },
          { name: 'Egg Curry', price: 200 },
        ],
      },
    ],
  },
  {
    id: 'tiffens',
    name: 'Tiffins',
    image: 'assets/images/tiffens.jpg',
    rating: 4,
    description: 'Choose from two or more outlets for South Indian breakfast',
    categories: ['Tiffins'],
    bestItem: 'Masala Dosa & Idli',
    menu: [
      {
        category: 'Breakfast & Snacks(Prices Revised By Restaurents)',
        items: [
          { name: 'Idli (4 pcs)', price: 55 },
          { name: 'Gare (4 pcs)', price: 55 },
          { name: 'Bajji (4 pcs)', price: 55 },
          { name: 'Mirchi Bajji (4 pcs)', price: 55 },
          { name: 'Punugulu', price: 55 },
          { name: 'Poori (2 pcs)', price: 50 },
        ],
      },
      {
        category: 'Dosa Corner',
        items: [
          { name: 'Masala Dosa', price: 65 },
          { name: 'Onion Dosa', price: 60 },
          { name: 'Single Egg Dosa', price: 60 },
          { name: 'Double Egg Dosa', price: 75 },
        ],
      },
      {
        category: 'Tawa Items',
        items: [
          { name: 'Chapati', price: 60 },
          { name: 'Parotha', price: 60 },
        ],
      },
    ],
  },
  {
    id: 'ruchi-pulkha-point',
    name: 'Ruchi Pulkha Point',
    image: 'assets/images/ruchi-pulkha.jpg',
    rating: 4,
    description: 'Best Pulkha & Egg Burji combos at budget prices',
    categories: ['Veg Meals'],
    bestItem: '3 Pulkha + Egg Burji Combo',
    menu: [
      {
        category: "Student's Choice",
        items: [
          { name: '3 Pulkhas + Egg Burji Combo', price: 60, isStudentChoice: true },
        ],
      },
      {
        category: 'Full Menu',
        items: [
          { name: '1 Pulka', price: 12 },
          { name: 'Only Egg Burji(Half)', price: 35 },
          { name: 'Only Egg Burji(Full)', price: 55 },
          { name: '3 Pulkas (2 Veg Curries)', price: 60 },
          { name: '3 Pulkas + Chicken Curry', price: 90 },
          { name: 'Single Egg Omelette', price: 25 },
          { name: 'Double Egg Omelette', price: 45 },
          { name: '2 Chapatis + 2 Veg Curries', price: 60 },
        ],
      },
    ],
  },
  {
    id: 'fruits',
    name: 'Fruit Market',
    image: 'assets/images/fruits.jpg',
    rating: 4,
    description: 'Fresh fruits available daily at market prices',
    categories: ['Fruits'],
    bestItem: 'Fresh Seasonal Fruits',
    menu: [
      {
        category: 'Fresh Fruits',
        items: [
          { name: 'Bananas 1kg', price: 60 },
          { name: 'Bananas 1/2kg', price: 35 },
          { name: 'Oranges 1kg', price: 110 },
          { name: 'Oranges 1/2kg', price: 60 },
          { name: 'Pomegranate 1kg', price: 210 },
          { name: 'Pomegranate 1/2kg', price: 110 },
          { name: 'Green Grapes 1kg', price: 210 },
          { name: 'Green Grapes 1/2kg', price: 110 },
          { name: 'Green Grapes 250g', price: 60 },
          { name: 'Black Grapes 1kg', price: 360 },
          { name: 'Black Grapes 1/2kg', price: 185 },
          { name: 'Black Grapes 250g', price: 100 },
          { name: 'Apples 1kg', price: 210 },
          { name: 'Apples 1/2kg', price: 110 },
        ],
      },
    ],
  },
];

export const categories = ['All','Haleem' ,'Biryani', 'Fast Food', 'Tiffins', 'Veg Meals', 'Fruits'];
